### ISSUE TITLE
De-duplicate page titles across front matter and content heading

### ISSUE THREAD

**Issue by mark-wiemer** [minetest/dev.luanti.org#41]
Front matter includes the page title, and that almost always matches the page's main heading. We're writing it twice, maybe we can just write it once somehow?

**Comment by wsor4035** [comment]
creating `/layouts/partials/docs/inject/content-before.html` with contents `<h1 id="{{ .Params.title | urlize }}">{{ .Params.title }} <a class="anchor" href="#{{ .Params.title | urlize }}">#</a></h1>` gets you 90% of the way there, problem is that its outside of the content article page which ......is bad. additionally since its outside you need to provide your own css for making the `#` only show on hover. this problem will require an upstream issue/pr be it for actual functionality or better partial option

**Comment by mark-wiemer** [comment]
Thanks for checking! I highly doubt this is worth any further effort, in favor of closing as "not planned" to clean up our backlog

**Comment by wsor4035** [comment]
if someone feels like figuring this out and getting a pr made, feel free, but not worth keeping an issue open forever on
