### ISSUE TITLE
Page edit link now redirects to GitHub :-(

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/dev.luanti.org#65]
I was disheartened to learn the new Dev Wiki no longer allows you to edit pages directly. Instead, you get a redirect to GitHub. 

??????

As someone who contributed to both wikis for years, this is very disappointing. Is the new wiki software (I don't even know what it is, but it's probably not MediaWiki) so bad it couldn't even be bothered to ship its own edit feature? Wow, that's quite a downgrade. Even the quickly-hacked-together Hedgewars Knowledge Base has a proper edit button.

Also, we should move AWAY from proprietary software (like GitHub), not start to embrace it more.

**Comment by rollerozxa** [comment]
> Instead, you get a redirect to GitHub. [...] Is the new wiki software (I don't even know what it is, but it's probably not MediaWiki) so bad it couldn't even be bothered to ship its own edit feature?

This is our way of doing page editing. It is a static website hosted in a Git repository and it has no server component, meaning it is very fast and there is nothing that can break or degrade by neglect like the MediaWiki instances hosting the previous Minetest Wikis that do not have functioning account registration, image thumbnailing and regular downtime due to running bloated software on a weak server.

Accepting pull requests from outside contributors makes it possible for everyone to make changes without needing to request an account, while curbing effectively all vandalism and spam. You know first hand what happens when an old account on an abandoned wiki gets compromised but there is nobody around with the necessary privileges to clean it up.

For members in the organisation (engine team, docs team, etc.) they should have been granted write access to the repo which lets them make edits directly from Git. I'd be okay with you getting write access too, just come down to #minetest-docs on IRC to discuss things.

Also:

> As someone who contributed to both wikis for years, this is very disappointing.

You're speaking from an extremely privileged standpoint as someone who did have an account on both wikis (as well as being a moderator there). For the vast majority of people in the community the wikis have been inaccessible from editing for years due to the arduous process of requesting an account not on one wiki, but two. Even when I was administrator on the old regular wiki it became difficult to create accounts for people once the mail server broke down and password reset emails didn't go out anymore.

> Also, we should move AWAY from proprietary software (like GitHub), not start to embrace it more.

Moving or mirroring would be as simple as adding another remote push URL to Codeberg, you should know that Git is decentralised and [there are ways to mirror between code forges both ways](https://codeberg.org/Recommendations/Mirror_to_Codeberg).

**Comment by mark-wiemer** [comment]
@Wuzzy2 from my understanding, this repo is very early in development and not yet serving as the "official" source of documentation in any way. Hence the lack of announcement, etc. GitHub is currently used as the host, but that's certainly change-able, and I'm in favor of re-opening this issue under the title "Consider moving to FOSS hosting site" or at least "Support FOSS PRs". It'd be a lot of work but I appreciate the value of FOSS, and I say this as an employee of Microsoft, which owns GitHub. (This is my personal account, everything I say here is my opinion, not Microsoft's.)

I think when you see this repo as a "newly in-development" project you'll understand why things are a bit janky currently and the edit process isn't super smooth. That said, reviewing documentation changes should be much, much less complicated than code changes for obvious reasons, and I don't anticipate PRs languishing at all.

Again, we could look into an in-site edit button, where changes are automatically pushed to a user branch and a PR is opened, heck we could even auto-merge small changes in the future. But this project is very new, so please be patient with updates of that nature, and feel free to open separate issues to discuss.

**Comment by mark-wiemer** [comment]
From wsor on #minetest-docs-irc: just going to drop the only cms like thing ive seen for github pages <https://github.com/pages-cms/pages-cms>

**Comment by SmallJoker** [comment]
I brought up similar concerns regarding the "ease of editing" here: https://irc.minetest.net/minetest-dev/2024-12-11#i_6226113

Ultimately, known contributors should get direct push permissions. Force pushing must be disallowed to avoid abuse.

**Comment by appgurueu** [comment]
> Ultimately, known contributors should get direct push permissions.

I agree. Note that the @minetest/docs team has direct push permissions. @Wuzzy2 do you want to be added? Can you think of someone else to be added?

**Comment by Wuzzy2** [comment]
What about the idea of moving to a very lightweight wiki software instead of going fully static? MediaWiki is admittedly a heavyweight. In the past I had good experiences with MoinMoinWiki (but this is just an example).

With a static website, it's impossible to ever add a TRUE edit button, only clunky workarounds.

I like Hugo, too, but I don't really think it can replace wikis well. I just think this fake "edit" link feels clunky, almost like an afterthought (it's a fake "edit" link because it doesn't edit, in only *proposes* edits at best).

Well, at least I can agree it was obviously bad the old wiki had serious downtime issues, especially in the recent past. So I understand that going back to MediaWiki is not an option, sadly.

**Comment by mark-wiemer** [comment]
@rollerozxa can we re-open this while we discuss?

**Comment by wsor4035** [comment]
Coming into this a few days late, sorry. first things first @Wuzzy2, please argue in good faith and stop making inflammatory posts/titles. I have edited them to be less so. regarding the actual issue here at hand, using github is an org level thing that is being followed, as for moving to another git platform, see https://github.com/minetest/minetest/issues/12324.

since this really has become two things together (git platform + editing is based on a git repo now), im going to reiterate that the first should go over to the linked issue above. just leaving this issue state as is for now since the org/repo has no policy of locking after $x days/$x days after close, etc

my personal opinion on that this already leans technical, so most people will be familiar with git and can use the tooling of there choice.

## cherrypicked responses to some things

> Also, the alternatives aren't even properly documented, i.e. which repo you have to clone, etc. If you are going to ignore anything else I say, please at least fix this.

see https://dev.luanti.org/about-this-site/ linked from the readme as well for setting up and contributing

> Also, at the end of the day, GitHub can't be fully circumvented anyway, right? I can fork and mirror as much as I want, but at the end of the day, I still have to shoehorn everything thru GitHub PRs at the end, right?

not really, you can always provide a patch, pr on another git host, etc (i think pgimeno has done this for minetest/minetest in the past?) but you will need someone to either pr it on your behalf or message a contributor to pull it in for you.

> I'm not too happy of having to trigger a full review process for every typo fix. OK, I may be the exception but what about the other wiki editors? :-/ I don't know if this will work out well in practice, given that Luanti reviews already can take months or years to complete. Do you believe that adding even more things people have to review is a good use of our limited resources?

i think here you are conflating the engines processes with this repo. that is code(mostly), this is documentation, completely different ball game(americanism, other countries have something..... i hope?). take a look at https://dev.luanti.org/about-this-site/#contribution-rules (NOTE the specific header section being linked to), currently contribution requirements are quite lax and while that probably wont remain that, i expect it still remain decently efficient/speedy. further more look at the prs that have been made so far, stuff has gone at a decent pace. additionally we have members in the docs that have proven quite efficient in other areas. while there is some overlap in members with the engine team, there also is others.

**Comment by mark-wiemer** [comment]
@Wuzzy2 please see #69 and #70 for more focused discussions on each other proposed change :) curious for your insights
