### ISSUE TITLE
[Discussion] Site framework

### ISSUE THREAD

**Issue by mark-wiemer** [minetest/dev.luanti.org#70]
Wuzzy suggested MoinMoinWiki as a possible alternative in #65, likely due to its built-in support of in-page editing (ref #69). We should either confirm that Hugo is the right choice or work to migrate to a better site framework

Pros of Hugo:
- Very fast to serve
- Easy to edit as a developer

Cons of Hugo:
- Does not easily support in-page editing (ref #69)

Lists not exhaustive ;)

**Comment by mark-wiemer** [comment]
Personally I'm OK with the status quo here as well. I believe there are some plugins that can create decent in-page editors, but honestly it's just not industry standard and not very valuable to this project. Looking forward to insights from others on feature Hugo may be missing that could be solved by other frameworks

**Comment by Wuzzy2** [comment]
MoinMoinWiki was just an example that stood in general for lightweight wiki softwares. I only suggested that one in particular because I have a bit of experience with it. I'm not too familiar with others.

As for performance and ease-of-maintenance, it's like a world of difference between MediaWiki and MoinMoinWiki. I assume the same for other lightweight wiki softwares because MediaWiki is a heavyweight. It has way more features than we will ever need anyway.

Question: Since it is also being discussed of the two wikis merging, will Luanti Wiki go Hugo as well?

If yes: For Luanti Wiki, the GitHub "edit" link will become even a bigger issue because I think it should be accessible to non-devs. Linking users to GitHub just to edit a wiki completely misses the point of a wiki. We should not expect from regular wiki editors to understand what a "pull request" or "branch" is. People will be greeted with a page full of features and terms that make zero sense to them. Because they are non-devs.
The point of a wiki is that it can be edited by non-devs. If people have to go through GitHub (or any dev platform for that matter, this isn't even a proprietary vs FOSS problem), the whole point of a wiki goes right out of the window. It just makes it needlessly complicated.
For the same reason, we use Weblate instead of requiring translators to edit the PO files themselves.

You have to understand, as developers, you are heavily biased towards your own workflow and believe it is "usable". Yes, but only to YOU. You can't just expect regular users to be willing to accept your workflow, especially if it's full of technobabble.

You can ignore everything I say, of course. But then don't complain to me when there are too few people willing to edit the wiki. GitHub (or even Codeberg) will be a significant hurdle for many.

OK, the Dev Wiki is a special case but again, I heard you want to merge both wikis, so that excuse no longer counts.

That's why I am still arguing to bring at least *some* lightweight wiki software back to the table.

**Comment by mark-wiemer** [comment]
We are making good progress towards an in-page editor, see #69. Pages CMS is our current best option but we haven't explored much.

That said, discussion on the IRC has heavily leaned away from the term "wiki" for our new documentation site. These pages are no longer meant to be edited by anyone under the sun. Instead, proposed changes should be made thoughtfully and only confirmed after review by a trusted Luanti community member. Back when Minetest was primarily MTG, it was OK to have missing or wrong information as it was just info about how players played a game. Now that Luanti has evolved into an entire platform, this documentation needs to be reviewed as incorrect information will confuse and frustrate developers as well as players. Playing a game is relatively easy compared to developing one: we need to be more careful with the documentation we provide to developers.

Again, you can see this difference across all software framework documentation vs game wikis: Software docs on the internet are not wikis, and popular wikis like for Minecraft, OSRS, or anything on Fandom, are not high-impact.

In short, we are changing doc edits to require a review process, and GitHub PRs are the current default for that. Per #69, we are looking at other options to generally streamline this workflow. But we still aim to require a review from a trusted Luanti community member before publishing any proposed change. As such, you'll see us decrease usage of the term "wiki" moving forward (with relatively low priority).

Per #19 and #64 the current goal of this project is to become the new one-and-only source of official Luanti documentation, yes. However, that will also mean changing "Luanti Wiki" to "Luanti Docs" or similar in the same spirit of "no more publishing unreviewed edits". Happy to discuss further over IRC, the docs channel has been nice and active recently and I'll post convo summaries in GitHub for better tracking :)

**Comment by appgurueu** [comment]
> I think it should be accessible to non-devs

Why? Since you've been active on the old wiki, can you name a few non-devs who contributed significantly?

With the new scope of this "wiki" (#64), which is supposed to explicitly *exclude* game-specific guides and similar (so no more MTG guides, those should be moved to the MTG repo or a separate page), I don't see why "non-devs" (excepting dev-adjacent people, like server admins) *should* need to edit, to a significant extent, *technical* documentation on how to use or develop Luanti.

As I've pointed out a few times already, I agree that "wiki" probably is a misleading name since it sets this expectation.

**Comment by rollerozxa** [comment]
Closing for a similar reason to #69 being closed.

I really don't think we should switch from a SSG to some more traditional wiki software, even if we don't end up dropping the wiki moniker in the future. And if we end up outscaling Hugo (which I don't think is very likely) then we can take that discussion about switching to another SSG once that would happen.
